### ISSUE TITLE
Data architectuur

### ISSUE THREAD

**Issue by koeenm** [fdnd-agency/deloitte#25]
We hebben van Robert informatie gekregen die we zelf in directus gaan zetten: 

<html><body>
<h3 dir="auto">Mobility Options</h3>
<p dir="auto"><strong>Cash:</strong></p>
<ul dir="auto">
<li>A gross cash amount is paid to you every month.</li>
<li>You are expected to manage your own transportation to and from work or client locations.</li>
<li>You can use Deloitte-subsidized transport options if desired.</li>
</ul>
<p dir="auto"><strong>Mobility +:</strong></p>
<ul dir="auto">
<li>Direct financial compensation is halved.</li>
<li>Public transport expenses are fully reimbursed for travel between 9 AM and 5 PM.</li>
</ul>
<p dir="auto"><strong>Lease Car:</strong></p>
<ul dir="auto">
<li>You receive a lease car provided by Deloitte.</li>
<li>Includes access to the Deloitte Business OV Card for public transport as needed.</li>
</ul>
<p dir="auto"><strong>Unlimited Public Transport:</strong></p>
<ul dir="auto">
<li>Unlimited access to public transport for work-related travel.</li>
</ul>
<p dir="auto"><strong>General Information:</strong></p>
<ul dir="auto">
<li><strong>Business OV Card:</strong> Everyone receives a "Business OV 
Card" for travel. The cost is deducted from the salary before tax, 
making travel more economical.</li>
<li><strong>Deloitte Bike System:</strong> Employees can lease a bike for a monthly fee.</li>
<li><strong>Bike Purchase:</strong> Employees can purchase a bike from their salary with tax benefits.</li>
<li><strong>Additional Features:</strong> The Business OV Card can also be used for renting bikes or cars when needed.</li>
</ul>
<h3 dir="auto">Job Grades and Mobility Options</h3>

Job Title | Mobility Options
-- | --
Partner | Cash, Mobility +, Lease Car, Unlimited Public Transport
Director | Cash, Mobility +, Lease Car, Unlimited Public Transport
Senior Manager | Cash, Mobility +, Lease Car, Unlimited Public Transport
Manager | Cash, Mobility +, Lease Car, Unlimited Public Transport
Senior Consultant | Cash, Mobility +
Consultant | Cash, Mobility +
Analyst | Mobility +

</body>
</html>

**Comment by Mossati** [comment]
### Beschrijving
Het datamodel voor Directus.
We hebben 4 tabellen voor Directus waarbij we data fetchen.

### Tabellen
- **Questions:** Dit tabel bevat alle vragen die wordne getoond in de wizard en elke vraag heeft een bepaald aantal punten.
- **Packages:** Dit tabel bevat alle mobiliteits opties voor transport met een job title eraan gelinkt.
- **Job_Title:** Dit tabel bevat alle titels die je kan krijgen als werknemer.
- **Users:** Dit tabel bevat de gegevens van de gebruikers met een package eraan gelinkt die je als resultaat terug krijgt van de wizard.

![Image](https://github.com/user-attachments/assets/d0f1aa31-c446-45c2-a989-5f1e52a661aa)
