### ISSUE TITLE
Overzichtspagina

### ISSUE THREAD

**Issue by koeenm** [fdnd-agency/deloitte#26]
# What this ticket includes 
- Research, what the best way is to built this component. 
- Gather links and information that could be useful for while building the component (Research)
- Build the component
- Component must be fully responsive
- Test the responsiveness

# Research 
> how did you come to this code or aesthetical decision 

Ik wil een pagina maken waarop je een overzicht hebt van de packages/mobility options en de algemene informatie. Voor de informatie op deze pagina maak ik gebruik van issue #25 

Ik heb dus 2 verschillende onderdelen op die pagina. Ik maak van deze verschillende componenten aparte bestanden aan in mijn project zodat ik de componenten handig kan herbruiken en aparte styling op deze kan toepassen.:

``` html
<script>
	export let data;
	import '../../styles/overview.css'
    import MobilityOptions from '$lib/mobility-options.svelte';
</script>

<main>
    <header>
            <h1>Overzicht</h1>
        <span>
            <a href="/wizard">Wizard</a>
            <a href="/inlog">Log in</a>
        </span>
    </header>

    <MobilityOptions/>
</main>
```

Hier is te zien hoe ik de mobility options vanuit een aparate file heb toegevoegd aan mijn main file.

De pagina is voor desktop only, dus ik zal niet mobile first gaan werken.

## Schetsen

Ik heb 4 mobility options, een beetje algemene informatie en job grades met mobility options. 

<img src="https://github.com/user-attachments/assets/9e7b5153-654f-4888-b51c-3b7c9b54dc0d" width=600>

### Breakdown schets

![Image](https://github.com/user-attachments/assets/f32c126e-7289-4238-a618-6605b5ff7fa3)

#### Design critique

...

## Pagina voor nu (29/09)

![Image](https://github.com/user-attachments/assets/c82c14a3-8f3c-4f2b-9c34-13ad00636ac4)

# conventions #4 
  Zoveel mogelijk werken in components (DRY)
- [x] Aparte CSS files als dit veel is 
- [ ] Mobile First 
- [ ] Comments toevoegen aan complexe code zodat dit voor iedereen in de squad te begrijpen is 
- [x] Kebab case 
- [ ] epic

 

**Links** 
- 

# Userstory
> Als gebruiker wil ik een duidelijk overzicht van de verschillende packages/mobility options en de algemene informatie

#  Reference 
> Media of how it can and maybe should look.

# Test

## How to execute the tests

- [ ] lighthouse
- [ ] tab
- [ ] user
- [ ] color contrast
- [ ] performance
- [ ] HTML validator

### Test results pagina van (29/09).

Tab test is te vinden in issue #30 .

**Comment by SamaraFellaDina** [comment]
# hoi

![](https://media.giphy.com/media/5iPc1mErXnOXwkRdxY/giphy.gif?cid=790b7611pkf2kkxnt3pfe1y1wmi8nm31fcut24wnb7gz3cd8&ep=v1_gifs_trending&rid=giphy.gif&ct=g)
