### ISSUE TITLE
Dialog functie mobility options component

### ISSUE THREAD

**Issue by koeenm** [fdnd-agency/deloitte#32]
Ik wil een dialog functie maken waardoor je meer informatie krijgt wanneer je op een mobility option klikt:

Ik denk dat het het beste is als ik dit met dynamische data, uit de database ga maken. Dan hoef ik maar 1 dialog te maken met daarin de informatie voor alle vier de opties

![Image](https://github.com/user-attachments/assets/315f40ab-947e-4947-9e3c-c13d8beb88fd)

![Image](https://github.com/user-attachments/assets/f9c4403c-ff97-4c31-a672-8753e4d16e6b)

## Links 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

**Comment by christoph3r3w** [comment]
In our last meeting with the cleint we learned that they prefer that we use dialogs for conformation events. so this idea will be shelved.
> meeting : #37
