### ISSUE TITLE
(De)briefing

### ISSUE THREAD

**Issue by christoph3r3w** [fdnd-agency/deloitte#7]
### **FDND Agency Deloitte** 

# Contact informatie
Naam: Robert Spier

Email: [robert.spier@gmail.com](mailto:robert.spier@gmail.com)

Contact opnemen via teams, vragen het liefst verzamelen.

# Achtergrondinformatie 

Deloitte, opgericht in 1845, is een multinationaal professioneel dienstverleningsbedrijf met een geschiedenis van 179 jaar. Het bedrijf biedt een breed scala aan diensten aan, variërend van consultancy, accountancy, marketing, audit, en risicobeheer tot vele andere bedrijfsaspecten. 
De organisatie heeft een aanzienlijke mondiale aanwezigheid met ongeveer 400.000 werknemers wereldwijd. In Nederland is Deloitte een belangrijke speler op de arbeidsmarkt met een personeelsbestand van circa 7.000 medewerkers.

# Opdrachtomschrijving 

Het doel is om een intern hulpmiddel (tool) te ontwikkel waarmee medewerkers van Deloitte Nederland gemakkelijk en prettig hun mobiliteitspakket kunnen kiezen.

### Wat is een mobiliteitspakket?

Een mobiliteitspakket is een set van vervoermogelijkheden die een bedrijf aan zijn werknemers aanbiedt. Dit kan bijvoorbeeld gaan over:
- 	Een leaseauto
- 	OV-abonnement
- 	Fietsplan
- 	Kilometervergoeding

# Aanleiding 

Er is momenteel een bestaand proces waarmee Deloitte-medewerkers hun mobiliteitspakket kunnen kiezen, maar de bijbehorende formulieren bevatten een aanzienlijke hoeveelheid specificaties , wat tijdrovend is om door te nemen. Deloitte streeft ernaar dit proces te vereenvoudigen, wat intern tijd en kosten kan besparen.

# Doelstelling 

Ontwikkel een web-app die een soepele ervaring biedt voor het kiezen van een mobiliteitspakket. Deze tool moet:
1.	Duidelijke en gedetailleerde informatie geven over de beschikbare pakketten
2.	Een verbeterde gebruikerservaring bieden
3.	Een stappenplan (wizard) bevatten om medewerkers te begeleiden bij het maken van keuzes

# Wat gaan we ontwikkelen

- 	Inlogpagina
- 	Landings-/profielpagina
- 	Algemene infopagina
- 	Gids voor pakketselectie (wizard)
- 	Formuliercomponenten
- 	Aangename UX

### Beschikbare middelen voor deze project:

1. Een Figma-bestand met richtlijnen voor het ontwerp
2. Data die beschikbaar zijn via een Directus API

### Bij deze sprint focussen we op: 

het aanpak en ontwikkeling van een stanndaart frontend praktijkvraagstuk 

# Gebruikers van het eindresultaat 

De gebruikers van dit product zijn alle medewerkers van Deloitte die in aanmerking komen voor mobiliteitspakketten.

# Oplevering 

### Wat moet er worden opgeleverd en wanneer?
We leveren een MVP-webapplicatie op die als intern hulpmiddel voor Deloitte kan worden gebruikt. De opleverdatum is gepland op 10 oktober 2024, aan Robert Spier.

 

# Randvoorwaarden
•	Desktop-first
•	Gebruiksvriendelijkheid
•	toepassing van hun conventies
•	Interne stijlgids
•	big details (animaties die bijdragen aan de UX)
•	Enjoy het proces ("have fun")

**Comment by roberrrt-s** [comment]
Hi allen, helemaal check- op het puntje Deloitte mederwerkers na, dat zijn er nu ruim 7000 volgens m'n laatste telling :).

**Comment by christoph3r3w** [comment]
It has been adjusted
