### ISSUE TITLE
Implementatie van mobiliteitswizard component

### ISSUE THREAD

**Issue by Mossati** [fdnd-agency/deloitte#9]
### Beschrijving
Dit project implementeert een wizard component als onderdeel van de mobiliteitsregeling website. 
De wizard bevat verschillende vragen die leiden tot een resultaat op basis van antwoorden en gebruikersrang.

**Comment by koeenm** [comment]
We zouden een `<dialog>` kunnen gebruiken om de wizard te maken:

![Image](https://github.com/user-attachments/assets/ce2b1c74-e6c2-4bf3-b5e5-34c820736542)

Hier is een link naar mijn code:

De code is niet geweldig en ik probeerde dit uit in sprint 9 dus we kunnen dit hooguit als klein opstapje gebruiken

https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/main/views/partials/aanmeld-form.ejs

**Comment by christoph3r3w** [comment]
In our last meeting with the cleint we learned that they prefer that we use dialogs for conformation events. so this idea will be shelved.
> meeting :
